version: "3.7" 
services:
  postgres1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password  
    volumes:  
        - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
        - postgres_data1:/var/lib/postgresql/data
  postgres2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
        - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
        - postgres_data2:/var/lib/postgresql/data
  postgres3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
        - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
        - postgres_data3:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    network_mode: "host"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      - postgres1
      - postgres2
      - postgres3
volumes:
    postgres_data1:
    postgres_data2:
    postgres_data3: